 query {
            landingPage{
              header{
                title
                subtitle
                description
              }
              sectionSale{
                title
                product{
                  name
                }
              }
            }
          }