 query {
            landingPage{
              header{
                logo{
                  name
                  url
                }
                title
              }
            }
          }